const fs = require('fs');

const path = 'messages/vi.json';
const json = JSON.parse(fs.readFileSync(path, 'utf8'));

// Cập nhật thủ công các mục bị lỗi
json.TeacherProfile = Object.assign(json.TeacherProfile || {}, {
  "default_teacher": "Giáo viên",
  "header_profile": "Hồ sơ giáo viên",
  "btn_change_avatar": "Đổi ảnh đại diện",
  "btn_edit_profile": "Sửa hồ sơ",
  "btn_close_edit": "Đóng chỉnh sửa",
  "stat_classrooms": "Lớp học",
  "stat_exams_created": "Bài thi đã tạo",
  "stat_exams_active": "Đang hoạt động",
  "stat_submissions": "Lượt nộp bài",
  "panel_info": "Thông tin cá nhân",
  "panel_expertise": "Chuyên môn",
  "panel_recent_exams": "Bài thi gần đây",
  "panel_auth_status": "Trạng thái tài khoản",
  "panel_update_profile": "Cập nhật hồ sơ",
  "panel_security": "Bảo mật",
  "panel_recent_classes": "Lớp học gần đây",
  "empty_info": "Chưa có thông tin bổ sung.",
  "empty_exams": "Chưa có bài thi nào.",
  "empty_classes": "Chưa có lớp học nào.",
  "lbl_email": "Email",
  "lbl_phone": "Số điện thoại",
  "lbl_title": "Chức danh",
  "lbl_department": "Tổ/Bộ môn",
  "lbl_workplace": "Đơn vị công tác",
  "lbl_schedule": "Lịch làm việc",
  "lbl_birthdate": "Ngày sinh",
  "lbl_gender": "Giới tính",
  "lbl_last_login": "Đăng nhập gần nhất",
  "lbl_bio": "Giới thiệu",
  "lbl_experience": "Kinh nghiệm",
  "lbl_certificates": "Chứng chỉ",
  "lbl_fullname": "Họ và tên",
  "lbl_current_pw": "Mật khẩu hiện tại",
  "lbl_new_pw": "Mật khẩu mới",
  "lbl_confirm_pw": "Nhập lại mật khẩu mới",
  "sec_verified": "Đã xác minh",
  "sec_unverified": "Chưa xác minh",
  "sec_enabled": "Đã bật",
  "sec_disabled": "Chưa bật",
  "btn_verify": "Xác thực",
  "btn_sending": "Đang gửi...",
  "btn_confirm": "Xác nhận",
  "btn_disable": "Tắt",
  "btn_send_enable": "Gửi mã bật",
  "btn_send_disable": "Gửi mã tắt",
  "btn_setup_pw": "Thiết lập mật khẩu",
  "btn_change_pw": "Đổi mật khẩu",
  "btn_save": "Lưu thay đổi",
  "btn_saving": "Đang lưu...",
  "placeholder_otp": "Nhập mã OTP",
  "msg_otp_sent_email": "Mã OTP 6 số đã được gửi về {email}. Nhập mã bên dưới để xác minh email.",
  "msg_otp_sent_2fa": "Mã OTP 6 số đã được gửi về email. Nhập mã bên dưới để {action} 2FA.",
  "pw_setup_title": "Thiết lập mật khẩu",
  "pw_setup_desc": "Tạo mật khẩu cho tài khoản này để lần sau có thể đăng nhập bằng email hoặc Google.",
  "pw_change_title": "Đổi mật khẩu",
  "pw_change_desc": "Cập nhật mật khẩu đăng nhập cho tài khoản của bạn.",
  "show_pw": "Hiện mật khẩu",
  "hide_pw": "Ẩn mật khẩu",
  "gender_not_updated": "Chưa cập nhật",
  "gender_male": "Nam",
  "gender_female": "Nữ",
  "gender_other": "Khác",
  "status_verified": "Đã xác minh",
  "status_verified_title": "Tài khoản đã được xác thực",
  "status_verified_desc": "Tài khoản giáo viên của bạn đã được xác thực thành công.",
  "status_pending": "Đang chờ duyệt",
  "status_pending_title": "Hồ sơ đang chờ duyệt",
  "status_pending_desc": "Quản trị viên đang xem xét thông tin xác thực của bạn.",
  "status_rejected": "Bị từ chối",
  "status_rejected_title": "Xác thực bị từ chối",
  "status_rejected_desc": "Vui lòng kiểm tra ghi chú và gửi lại thông tin xác thực.",
  "status_standard": "Tài khoản tiêu chuẩn",
  "status_standard_title": "Chưa xác thực giáo viên",
  "status_standard_desc": "Xác thực tài khoản để mở đầy đủ tính năng giáo viên.",
  "action_resend_verify": "Gửi lại xác thực",
  "action_verify_now": "Xác thực ngay",
  "note": "Ghi chú: {note}",
  "submitted_at": "Đã gửi: {time}",
  "verified_at": "Đã xác minh: {time}",
  "unnamed_exam": "Bài thi chưa đặt tên",
  "questions_count": "{count} câu hỏi",
  "duration_minutes": "{count} phút",
  "view_results": "Xem kết quả",
  "default_class": "Lớp học",
  "no_class_code": "Chưa có mã lớp",
  "toast_avatar_invalid": "Chỉ chấp nhận file ảnh.",
  "toast_avatar_success": "Cập nhật ảnh đại diện thành công.",
  "toast_avatar_error": "Không thể cập nhật ảnh đại diện.",
  "toast_profile_success": "Thông tin giáo viên đã được cập nhật.",
  "toast_profile_error": "Vui lòng kiểm tra lại thông tin.",
  "toast_pw_mismatch": "Mật khẩu xác nhận không khớp.",
  "toast_pw_setup_success": "Thiết lập mật khẩu thành công.",
  "toast_pw_change_success": "Đổi mật khẩu thành công.",
  "toast_pw_error": "Không thể cập nhật mật khẩu.",
  "toast_email_verify_already": "Email đã được xác minh.",
  "toast_email_verify_sent": "Mã xác minh đã được gửi về email.",
  "toast_email_verify_success": "Xác minh email thành công.",
  "toast_email_verify_error": "Không thể xác minh email.",
  "toast_error_load": "Không tải được dữ liệu. Vui lòng thử lại sau.",
  "toast_otp_missing": "Vui lòng nhập mã OTP 6 số.",
  "toast_2fa_sent": "Mã OTP 2FA đã được gửi.",
  "toast_2fa_enabled": "Đã bật 2FA.",
  "toast_2fa_disabled": "Đã tắt 2FA.",
  "toast_2fa_error": "Không thể cập nhật 2FA."
});

json.StudentProfile = Object.assign(json.StudentProfile || {}, {
  "btn_close": "Đóng chỉnh sửa",
  "change_photo": "Đổi ảnh đại diện",
  "update_title": "Cập nhật hồ sơ",
  "field_fullname": "Họ và tên",
  "field_student_id": "Mã học sinh",
  "field_class": "Lớp",
  "field_program": "Chương trình học",
  "field_phone": "Số điện thoại",
  "gender_female": "Nữ",
  "gender_other": "Khác",
  "btn_saving": "Đang lưu...",
  "btn_save": "Lưu thay đổi",
  "detail_phone": "Số điện thoại",
  "detail_dob": "Ngày sinh",
  "detail_gender": "Giới tính",
  "not_updated": "Chưa cập nhật",
  "pw_current": "Mật khẩu hiện tại",
  "pw_new": "Mật khẩu mới",
  "pw_confirm": "Xác nhận mật khẩu",
  "btn_pw_processing": "Đang xử lý...",
  "btn_pw_update": "Cập nhật mật khẩu",
  "summary_exams": "Bài thi đã làm",
  "summary_avg": "Điểm trung bình",
  "results_title": "Kết quả gần đây",
  "col_exam": "Bài thi",
  "col_date": "Nộp lúc",
  "col_score": "Điểm",
  "col_status": "Trạng thái",
  "status_pass": "Đạt",
  "status_fail": "Chưa đạt",
  "no_data": "Chưa có dữ liệu.",
  "pw_mismatch": "Mật khẩu xác nhận không khớp.",
  "pw_error": "Không thể cập nhật mật khẩu.",
  "avatar_type_error": "Chỉ chấp nhận file ảnh.",
  "avatar_success": "Cập nhật ảnh đại diện thành công.",
  "avatar_error": "Không thể cập nhật ảnh đại diện.",
  "profile_success": "Cập nhật hồ sơ thành công.",
  "profile_error": "Có lỗi xảy ra khi lưu hồ sơ.",
  "default_name": "Học sinh",
  "panel_info": "Thông tin cá nhân",
  "empty_info": "Chưa có thông tin bổ sung.",
  "panel_security": "Bảo mật",
  "lbl_last_login": "Đăng nhập gần nhất",
  "sec_verified": "Đã xác minh",
  "sec_unverified": "Chưa xác minh",
  "sec_enabled": "Đã bật",
  "sec_disabled": "Chưa bật",
  "btn_verify": "Xác thực",
  "btn_sending": "Đang gửi...",
  "btn_confirm": "Xác nhận",
  "btn_disable": "Tắt",
  "btn_send_enable": "Gửi mã bật",
  "btn_send_disable": "Gửi mã tắt",
  "placeholder_otp": "Nhập mã OTP",
  "msg_otp_sent_email": "Mã OTP 6 số đã được gửi về {email}. Nhập mã bên dưới để xác minh email.",
  "msg_otp_sent_2fa": "Mã OTP 6 số đã được gửi về email. Nhập mã bên dưới để {action} 2FA.",
  "pw_setup_title": "Thiết lập mật khẩu",
  "pw_setup_desc": "Tạo mật khẩu để có thể đăng nhập bằng email/mật khẩu ngoài Google.",
  "pw_change_title": "Đổi mật khẩu",
  "pw_change_desc": "Cập nhật mật khẩu đăng nhập cho tài khoản của bạn.",
  "btn_setup_pw": "Thiết lập mật khẩu",
  "show_pw": "Hiện mật khẩu",
  "hide_pw": "Ẩn mật khẩu",
  "stat_best": "Điểm cao nhất",
  "stat_pass": "Tỉ lệ đạt",
  "toast_error_load": "Không tải được dữ liệu. Vui lòng thử lại sau.",
  "toast_pw_setup_success": "Thiết lập mật khẩu thành công.",
  "toast_pw_change_success": "Đổi mật khẩu thành công.",
  "toast_email_verify_already": "Email đã được xác minh.",
  "toast_email_verify_sent": "Mã xác minh đã được gửi về email.",
  "toast_email_verify_success": "Xác minh email thành công.",
  "toast_email_verify_error": "Không thể xác minh email.",
  "toast_otp_missing": "Vui lòng nhập mã OTP 6 số.",
  "toast_2fa_sent": "Mã OTP 2FA đã được gửi.",
  "toast_2fa_enabled": "Đã bật 2FA.",
  "toast_2fa_disabled": "Đã tắt 2FA.",
  "toast_2fa_error": "Không thể cập nhật 2FA."
});

if (json.TeacherExams) {
  json.TeacherExams.header = Object.assign(json.TeacherExams.header || {}, {
    "breadcrumb_parent": "Kho đề",
    "breadcrumb_current": "Biên soạn",
    "title": "Biên soạn đề thi"
  });
  json.TeacherExams.generating = Object.assign(json.TeacherExams.generating || {}, {
    "title": "Đang phân tích tài liệu...",
    "log_start": "Đang khởi tạo tiến trình...",
    "log_uploading": "Đang tải lên và xử lý...",
    "log_extract": "AI đang trích xuất nội dung văn bản...",
    "log_analyze": "Đang phân tích cấu trúc và nhận diện câu hỏi...",
    "log_optimize": "Đang chuẩn hóa định dạng và trích xuất hình ảnh...",
    "log_prepare": "Đang đóng gói dữ liệu và hoàn thiện...",
    "log_done": "Hoàn tất! Đang chuyển sang màn hình kiểm tra...",
    "progress_label": "Tiến trình",
    "progress_value": "Đang xử lý..."
  });
  json.TeacherExams.toast = Object.assign(json.TeacherExams.toast || {}, {
    "invalid_count": "Vui lòng nhập số câu hỏi hợp lệ.",
    "session_expired": "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.",
    "empty_response": "Không nhận được dữ liệu từ máy chủ.",
    "upload_error": "Không thể xử lý file.",
    "connection_error": "Không thể kết nối máy chủ.",
    "timeout": "Quá thời gian xử lý. Vui lòng thử lại với tệp nhỏ hơn.",
    "generate_success": "AI đã biên soạn thành công!",
    "ai_failed": "AI xử lý thất bại: ",
    "extract_success": "Trích xuất thành công {count} câu hỏi!",
    "invalid_title": "Vui lòng nhập tên đề thi.",
    "invalid_duration": "Vui lòng nhập thời gian làm bài hợp lệ.",
    "invalid_versions": "Vui lòng nhập số mã đề hợp lệ.",
    "empty_questions": "Đề thi phải có ít nhất 1 câu hỏi.",
    "publish_success": "Đề thi đã được công bố!",
    "draft_success": "Đã lưu bản nháp thành công!"
  });
  json.TeacherExams.warning = Object.assign(json.TeacherExams.warning || {}, {
    "title": "Lưu ý quan trọng",
    "text": "Công cụ này sử dụng AI để phân tích tài liệu. Xin vui lòng kiểm tra lại chất lượng câu hỏi trước khi xuất bản."
  });
  json.TeacherExams.upload = Object.assign(json.TeacherExams.upload || {}, {
    "title_ai": "Tải tài liệu để AI tự động tạo câu hỏi",
    "title_import": "Tải lên file DOCX/PDF để trích xuất câu hỏi",
    "hint": "Hỗ trợ các định dạng PDF, Word, TXT - tối đa 25MB",
    "btn_choose": "Chọn tệp từ máy tính",
    "label_count": "Số lượng câu hỏi muốn tạo",
    "btn_generate": "Bắt đầu tạo câu hỏi",
    "btn_extract": "Bắt đầu trích xuất"
  });
  json.TeacherExams.empty = Object.assign(json.TeacherExams.empty || {}, {
    "title": "Chưa có câu hỏi nào",
    "desc": "Bạn đang ở chế độ tạo đề thi thủ công. Hãy bắt đầu bằng việc thêm câu hỏi đầu tiên cho đề thi của bạn.",
    "btn_add": "Thêm câu hỏi đầu tiên"
  });
  json.TeacherExams.list = Object.assign(json.TeacherExams.list || {}, {
    "title": "Danh sách câu hỏi",
    "btn_add": "Thêm câu hỏi mới",
    "q_prefix": "Câu",
    "no_content": "Chưa có nội dung",
    "tooltip_add_img": "Thêm hình ảnh",
    "tooltip_edit": "Chỉnh sửa câu hỏi",
    "tooltip_done": "Xong chỉnh sửa",
    "tooltip_delete": "Xóa"
  });
}

fs.writeFileSync(path, JSON.stringify(json, null, 2), 'utf8');
console.log('Fixed json file');
